// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://csszqhhkjgsqgdvdafxt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzc3pxaGhramdzcWdkdmRhZnh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDUyMTM4MjMsImV4cCI6MjA2MDc4OTgyM30.8vJUrJ4dSZZ_45FPIHA-4mABsSL4NGp31_msLbpKzFA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);